# -*- coding: utf-8 -*-
"""predict_ML.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xq26HMvGBeGUn7-UilxcfVh03X4CpgRr
"""

## TFIDF MODEL PATH & LOGISTIC REGRESSION MODEL PATH
logistic_path = 'LogisticReg_acc98_full.joblib'
tfidf_path = 'tfidf.joblib'

## LOAD WEIGHTS
from joblib import dump, load
clf = load(logistic_path) 
fit_tfidf = load(tfidf_path )

import re
import string
from string import punctuation
import numpy as np
import pandas as pd
import random
import missingno
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.base import TransformerMixin
from sklearn.metrics import accuracy_score, recall_score, plot_confusion_matrix

def predict_ML(client_msg):
  '''take client message string
     return ML model predicted label
  '''
  msg_tfidf = fit_tfidf.transform(client_msg).toarray()
  return clf.predict(msg_tfidf)